services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer # Bản Developer miễn phí cho dev
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

volumes:
  mssql_data: