package dao;

import database.DatabaseConnection;
import entity.ChiTietHoaDon;
import entity.enums.LoaiChiTietHoaDon;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.List;

public class ChiTietHoaDonDAO {

    private static final Logger LOGGER = Logger.getLogger(ChiTietHoaDonDAO.class.getName());

    private Connection getConn() throws SQLException {
        return DatabaseConnection.getInstance().getConnection();
    }

    public List<ChiTietHoaDon> getByHoaDon(String maHoaDon) {
        List<ChiTietHoaDon> list = new ArrayList<>();
        String sql = "SELECT * FROM ChiTietHoaDon WHERE maHoaDon=?";
        try (PreparedStatement ps = getConn().prepareStatement(sql)) {
            ps.setString(1, maHoaDon);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) list.add(mapRow(rs));
        } catch (SQLException e) { LOGGER.log(Level.SEVERE, "Database error in ChiTietHoaDonDAO", e); }
        return list;
    }

    public boolean insert(ChiTietHoaDon ct) {
        String sql = "INSERT INTO ChiTietHoaDon(maHoaDon, loai, moTa, soLuong, donGia, thanhTien) " +
                     "VALUES(?,?,?,?,?,?)";
        try (PreparedStatement ps = getConn().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, ct.getHoaDon().getMaHoaDon());
            
            // Map PHU_PHI to DICH_VU to satisfy DB CHECK constraint
            String loai = ct.getLoaiChiTiet() != null ? ct.getLoaiChiTiet().name() : "PHONG";
            if ("PHU_PHI".equals(loai)) loai = "DICH_VU"; 
            ps.setString(2, loai);
            
            ps.setString(3, ct.getNoiDung());
            ps.setInt(4, ct.getSoLuong());
            ps.setDouble(5, ct.getDonGia());
            ps.setDouble(6, ct.getThanhTien());
            
            int affectedRows = ps.executeUpdate();
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        ct.setMaChiTietHoaDon(String.valueOf(generatedKeys.getInt(1)));
                    }
                }
                return true;
            }
            return false;
        } catch (SQLException e) { LOGGER.log(Level.SEVERE, "Database error in ChiTietHoaDonDAO", e); return false; }
    }

    public String generateMaCTHD() {
        return ""; // ID is generated by database IDENTITY
    }

    private ChiTietHoaDon mapRow(ResultSet rs) throws SQLException {
        ChiTietHoaDon ct = new ChiTietHoaDon();
        ct.setMaChiTietHoaDon(String.valueOf(rs.getInt("maChiTiet")));
        
        String loaiStr = rs.getString("loai");
        if (loaiStr != null) {
            try {
                ct.setLoaiChiTiet(LoaiChiTietHoaDon.valueOf(loaiStr.toUpperCase()));
            } catch (IllegalArgumentException e) {
                ct.setLoaiChiTiet(LoaiChiTietHoaDon.PHONG);
            }
        }
        
        ct.setNoiDung(rs.getString("moTa"));
        ct.setSoLuong(rs.getInt("soLuong"));
        ct.setDonGia(rs.getDouble("donGia"));
        ct.setThanhTien(rs.getDouble("thanhTien"));
        
        return ct;
    }
}


